server:
  port: 8080
logging:
    file: /data/logs/digger/digger.log
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123abc123abc
        url: jdbc:mysql://localhost:3306/digger?characterEncoding=UTF-8
        username: root
